// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetailSection: typeof import('./src/components/detail-section/detail-section.vue')['default']
    HouseItemV3: typeof import('./src/components/house-item-v3/house-item-v3.vue')['default']
    HouseItemV9: typeof import('./src/components/house-item-v9/house-item-v9.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
